const menuBtn = document.querySelector('.menu-toggle');
const nav = document.querySelector('.nav');
menuBtn.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuBtn.setAttribute('aria-expanded', open); menuBtn.textContent = open ? '×' : '☰'; });
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { nav.classList.remove('open'); menuBtn.setAttribute('aria-expanded', 'false'); menuBtn.textContent = '☰'; }));

const io = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('on'); io.unobserve(e.target); } }), { threshold: .12 });
document.querySelectorAll('.reveal').forEach(el => io.observe(el));

let counted = false; const stats = document.querySelector('.stats');
if (stats) { const counterObs = new IntersectionObserver(([e]) => { if (e.isIntersecting && !counted) { counted = true; document.querySelectorAll('[data-count]').forEach(el => { const target = +el.dataset.count; let n = 0; const step = Math.max(1, Math.ceil(target / 28)); const t = setInterval(() => { n = Math.min(target, n + step); el.textContent = n; if (n === target) clearInterval(t); }, 45); }); counterObs.disconnect(); } }, { threshold: .3 }); counterObs.observe(stats); }

// Equipamentos: explicações rápidas sem abrir outra página.
const gearDetail = document.getElementById('gear-detail');
document.querySelectorAll('.gear-card').forEach(card => card.addEventListener('click', () => { gearDetail.textContent = card.dataset.detail; document.querySelectorAll('.gear-card').forEach(c => c.removeAttribute('aria-current')); card.setAttribute('aria-current', 'true'); }));

/* GALERIA: adicione fotos no array abaixo. category: operacoes | treinos | equipe | bastidores */
const galleryImages = [
  { src:'assets/hero.jpg', title:'Operação urbana', alt:'Operador da Filhos de Asgard em cenário tático', category:'operacoes' },
  { src:'assets/batalha.jpg', title:'Zona de combate', alt:'Registro de cenário de batalha de airsoft', category:'operacoes' }
];
const galleryGrid = document.getElementById('gallery-grid'); const galleryCount = document.getElementById('gallery-count'); const loadMoreBtn = document.getElementById('load-more');
const PAGE_SIZE = 8; let rendered = 0; let activeFilter = 'all';
function filteredImages(){ return activeFilter === 'all' ? galleryImages : galleryImages.filter(i => i.category === activeFilter); }
function renderGallery(reset=false){ if(reset){ rendered=0; galleryGrid.innerHTML=''; } const list=filteredImages(); const end=Math.min(rendered+PAGE_SIZE,list.length); const frag=document.createDocumentFragment(); for(let i=rendered;i<end;i++){ const p=list[i]; const button=document.createElement('button'); button.className='gallery-card'; button.type='button'; button.dataset.src=p.src; button.setAttribute('aria-label',`Ampliar foto: ${p.title}`); button.innerHTML=`<img src="${p.src}" alt="${p.alt}" loading="lazy" decoding="async"><span>${p.title}</span>`; frag.appendChild(button); } galleryGrid.appendChild(frag); rendered=end; galleryCount.textContent=`${list.length} ${list.length===1?'foto':'fotos'}`; loadMoreBtn.hidden=rendered>=list.length; }
renderGallery(); loadMoreBtn.addEventListener('click',()=>renderGallery());
document.querySelectorAll('.gallery-filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.gallery-filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;renderGallery(true);}));

const lightbox=document.getElementById('lightbox'); const lightImg=lightbox.querySelector('img'); const lightCaption=lightbox.querySelector('.lightbox-caption'); let currentPhoto=0;
function currentList(){return filteredImages();} function showPhoto(index){const list=currentList(); if(!list.length)return; currentPhoto=(index+list.length)%list.length; const p=list[currentPhoto]; lightImg.src=p.src; lightImg.alt=p.alt; lightCaption.textContent=`${p.title} • ${currentPhoto+1} / ${list.length}`;}
galleryGrid.addEventListener('click',e=>{const card=e.target.closest('.gallery-card');if(!card)return;const list=currentList();const idx=list.findIndex(p=>p.src===card.dataset.src);showPhoto(idx);lightbox.showModal();});
lightbox.querySelector('.prev').addEventListener('click',()=>showPhoto(currentPhoto-1)); lightbox.querySelector('.next').addEventListener('click',()=>showPhoto(currentPhoto+1)); lightbox.querySelector('.modal-close').addEventListener('click',()=>lightbox.close());
lightbox.addEventListener('click',e=>{const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close();});
document.addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')showPhoto(currentPhoto-1);if(e.key==='ArrowRight')showPhoto(currentPhoto+1);});

// Portal do recruta: orientação personalizada, processada somente no navegador.
const recruitForm=document.getElementById('recruit-form'); const recruitResult=document.getElementById('recruit-result');
recruitForm.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(recruitForm);const experience=fd.get('experience'),gear=fd.get('gear'),interest=fd.get('interest');let title='Seu próximo passo';let msg='';if(experience==='never') msg+='Como é sua primeira experiência, priorize conversar com a equipe, entender as regras e participar do briefing com atenção. ';else msg+='Como você já teve contato com o esporte, vale alinhar com a equipe o formato do próximo evento e as regras do campo. ';if(gear==='none') msg+='Não compre tudo de uma vez: descubra primeiro o que realmente é necessário e quais opções fazem sentido para você. ';else if(gear==='partial') msg+='Leve sua lista de equipamentos para confirmar com a organização o que atende às regras do evento. ';else msg+='Confira se seu equipamento está de acordo com as exigências específicas do campo e da operação. ';const interests={strategy:'Seu interesse por estratégia combina com funções de comunicação, coordenação e leitura de cenário.',action:'Seu interesse por movimentação pode combinar com funções mais dinâmicas; comece simples e aprenda o ritmo do campo.',community:'Seu interesse pela comunidade é um ótimo ponto de partida: o airsoft depende muito de convivência, respeito e confiança.'};msg+=' '+interests[interest];recruitResult.innerHTML=`<strong>${title}</strong>${msg}<br><br><a class="btn btn-primary" href="#redes">Falar com a equipe</a>`;recruitResult.hidden=false;recruitResult.scrollIntoView({behavior:'smooth',block:'center'});});

// Links sociais ainda não configurados.
document.querySelectorAll('[data-configure-link]').forEach(link=>link.addEventListener('click',e=>{if(link.getAttribute('href')==='#')e.preventDefault();}));
document.getElementById('year').textContent=new Date().getFullYear();

// Chamas ciano em canvas, responsivas e reduzidas em mobile/prefers-reduced-motion.
(()=>{const canvas=document.getElementById('cyan-flames');if(!canvas)return;const ctx=canvas.getContext('2d',{alpha:true});const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let w=0,h=0,dpr=1,particles=[],raf=0,last=0;const rand=(a,b)=>a+Math.random()*(b-a);function resize(){dpr=Math.min(window.devicePixelRatio||1,1.5);w=innerWidth;h=innerHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);const target=reduceMotion?34:Math.max(52,Math.min(115,Math.round(w/7)));particles=Array.from({length:target},()=>makeFlame(true));}function makeFlame(initial=false){const s=Math.random();let x;if(s<.28)x=rand(-30,w*.23);else if(s>.72)x=rand(w*.77,w+30);else x=rand(0,w);return{x,y:initial?rand(h*.48,h+60):h+rand(10,90),r:rand(12,42)*(w<600?.78:1),vy:rand(.45,1.45),vx:rand(-.22,.22),phase:rand(0,Math.PI*2),life:rand(.65,1),decay:rand(.0018,.0042)}}function draw(){ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation='lighter';const fg=ctx.createLinearGradient(0,h,0,h*.55);fg.addColorStop(0,'rgba(0,210,245,.075)');fg.addColorStop(.48,'rgba(0,130,180,.018)');fg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=fg;ctx.fillRect(0,h*.45,w,h*.55);for(let i=0;i<particles.length;i++){const p=particles[i];p.phase+=.025;p.y-=p.vy;p.x+=p.vx+Math.sin(p.phase)*.16;p.life-=p.decay;if(p.life<=0||p.y<h*.28)particles[i]=makeFlame(false);const q=particles[i],stretch=q.r*2.7,alpha=Math.max(0,q.life)*.18;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(Math.sin(q.phase*.8)*.08);ctx.scale(1,1.7);const g=ctx.createRadialGradient(0,0,0,0,0,q.r);g.addColorStop(0,`rgba(165,248,255,${alpha*.82})`);g.addColorStop(.22,`rgba(23,221,249,${alpha})`);g.addColorStop(.55,`rgba(0,146,194,${alpha*.48})`);g.addColorStop(1,'rgba(0,82,120,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,-stretch*.48);ctx.bezierCurveTo(q.r*.7,-q.r*.65,q.r*.8,q.r*.25,0,q.r);ctx.bezierCurveTo(-q.r*.8,q.r*.25,-q.r*.6,-q.r*.55,0,-stretch*.48);ctx.fill();ctx.restore()}ctx.globalCompositeOperation='source-over'}function loop(t){if(t-last>30){draw();last=t}raf=requestAnimationFrame(loop)}let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(resize,120)},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else if(!reduceMotion)raf=requestAnimationFrame(loop)});resize();draw();if(!reduceMotion)raf=requestAnimationFrame(loop)})();
